name: CI

on:
  push:
    branches:
      - "!main"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - name: Update NPM
        run: npm install -g npm
      - name: NPM Install
        run: npm ci
      - name: Run unit tests
        run: npm run test
